name: um papo
url: http://umpapo.com
url: http://zachholman.com
description: um papo com...
facebook: umpapo
twitter: umpapocom
pygments: true
safe: true
lsi: false
markdown: redcarpet
exclude: ['README',  'CNAME']
permalink: /:title
gravatar_url: http://gravatar.com/avatar/0c22ed10d238d09c59c2d897f444ad12