name: um papo
url: http://umpapo.com
description: um papo com...
pygments: true
safe: true
lsi: false
markdown: redcarpet
exclude: ['README',  'CNAME']
permalink: /:title
facebook: umpapo
twitter: umpapocom
gravatar_martinusso: http://gravatar.com/avatar/0c22ed10d238d09c59c2d897f444ad12
gravatar_isaura: 